// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vgrpc.proto

package vgrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// pi input
type PiRequest struct {
	N                    int32    `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PiRequest) Reset()         { *m = PiRequest{} }
func (m *PiRequest) String() string { return proto.CompactTextString(m) }
func (*PiRequest) ProtoMessage()    {}
func (*PiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_df0ee5f0ae727d14, []int{0}
}

func (m *PiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PiRequest.Unmarshal(m, b)
}
func (m *PiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PiRequest.Marshal(b, m, deterministic)
}
func (m *PiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PiRequest.Merge(m, src)
}
func (m *PiRequest) XXX_Size() int {
	return xxx_messageInfo_PiRequest.Size(m)
}
func (m *PiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PiRequest proto.InternalMessageInfo

func (m *PiRequest) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

// pi output
type PiResponse struct {
	Out                  string   `protobuf:"bytes,1,opt,name=out,proto3" json:"out,omitempty"`
	Value                float64  `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PiResponse) Reset()         { *m = PiResponse{} }
func (m *PiResponse) String() string { return proto.CompactTextString(m) }
func (*PiResponse) ProtoMessage()    {}
func (*PiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df0ee5f0ae727d14, []int{1}
}

func (m *PiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PiResponse.Unmarshal(m, b)
}
func (m *PiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PiResponse.Marshal(b, m, deterministic)
}
func (m *PiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PiResponse.Merge(m, src)
}
func (m *PiResponse) XXX_Size() int {
	return xxx_messageInfo_PiResponse.Size(m)
}
func (m *PiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PiResponse proto.InternalMessageInfo

func (m *PiResponse) GetOut() string {
	if m != nil {
		return m.Out
	}
	return ""
}

func (m *PiResponse) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// pi input
type PingRequest struct {
	Params               string   `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_df0ee5f0ae727d14, []int{2}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetParams() string {
	if m != nil {
		return m.Params
	}
	return ""
}

// pi output
type PingResponse struct {
	Out                  string   `protobuf:"bytes,1,opt,name=out,proto3" json:"out,omitempty"`
	Result               string   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df0ee5f0ae727d14, []int{3}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetOut() string {
	if m != nil {
		return m.Out
	}
	return ""
}

func (m *PingResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*PiRequest)(nil), "vgrpc.PiRequest")
	proto.RegisterType((*PiResponse)(nil), "vgrpc.PiResponse")
	proto.RegisterType((*PingRequest)(nil), "vgrpc.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "vgrpc.PingResponse")
}

func init() { proto.RegisterFile("vgrpc.proto", fileDescriptor_df0ee5f0ae727d14) }

var fileDescriptor_df0ee5f0ae727d14 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x8d, 0xd2, 0x60, 0xa7, 0x7b, 0x58, 0x47, 0x59, 0xd6, 0x3d, 0x2d, 0x01, 0x61, 0x4f,
	0x15, 0xfc, 0x03, 0xde, 0x3d, 0x78, 0x2d, 0xf1, 0x13, 0xc4, 0x10, 0x4a, 0xa0, 0x26, 0x31, 0x7f,
	0xfa, 0xf9, 0xa5, 0x49, 0x5b, 0xf4, 0xb0, 0xb7, 0xfc, 0x66, 0xe6, 0xbd, 0xc9, 0x1b, 0x68, 0xc6,
	0xde, 0x3b, 0xd9, 0x3a, 0x6f, 0xa3, 0xc5, 0x2a, 0x03, 0xbb, 0x87, 0xba, 0xd3, 0x5c, 0xfd, 0x24,
	0x15, 0x22, 0x6e, 0x80, 0x98, 0x3d, 0x39, 0x92, 0x53, 0xc5, 0x89, 0x61, 0x2f, 0x00, 0x53, 0x2b,
	0x38, 0x6b, 0x82, 0xc2, 0x2d, 0x5c, 0xd9, 0x14, 0x73, 0xb7, 0xe6, 0xd3, 0x13, 0xef, 0xa0, 0x1a,
	0xc5, 0x90, 0xd4, 0xfe, 0xf2, 0x48, 0x4e, 0x84, 0x17, 0x60, 0x0f, 0xd0, 0x74, 0xda, 0xf4, 0x8b,
	0xe5, 0x0e, 0xa8, 0x13, 0x5e, 0x7c, 0x87, 0x59, 0x39, 0x13, 0x7b, 0x83, 0x4d, 0x19, 0x3b, 0x6b,
	0xbf, 0x03, 0xea, 0x55, 0x48, 0x43, 0xcc, 0xfe, 0x35, 0x9f, 0xe9, 0x29, 0x41, 0xf3, 0xe1, 0x9d,
	0xfc, 0x54, 0x7e, 0xd4, 0x52, 0xe1, 0x23, 0xd0, 0x4e, 0xbf, 0x8b, 0x41, 0xe2, 0xb6, 0x2d, 0xf9,
	0xd6, 0x3c, 0x87, 0x9b, 0x3f, 0x95, 0xb2, 0x87, 0x5d, 0xe0, 0x2b, 0x5c, 0x4f, 0x9b, 0xb3, 0x04,
	0xd7, 0x81, 0xf5, 0xc7, 0x87, 0xdb, 0x7f, 0xb5, 0x45, 0xf6, 0x45, 0xf3, 0xd9, 0x9e, 0x7f, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xc4, 0x2d, 0x66, 0xf4, 0x45, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrpcServiceClient is the client API for GrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcServiceClient interface {
	// pi method
	PiCalc(ctx context.Context, in *PiRequest, opts ...grpc.CallOption) (*PiResponse, error)
	PingCalc(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type grpcServiceClient struct {
	cc *grpc.ClientConn
}

func NewGrpcServiceClient(cc *grpc.ClientConn) GrpcServiceClient {
	return &grpcServiceClient{cc}
}

func (c *grpcServiceClient) PiCalc(ctx context.Context, in *PiRequest, opts ...grpc.CallOption) (*PiResponse, error) {
	out := new(PiResponse)
	err := c.cc.Invoke(ctx, "/vgrpc.GrpcService/PiCalc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcServiceClient) PingCalc(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/vgrpc.GrpcService/PingCalc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcServiceServer is the server API for GrpcService service.
type GrpcServiceServer interface {
	// pi method
	PiCalc(context.Context, *PiRequest) (*PiResponse, error)
	PingCalc(context.Context, *PingRequest) (*PingResponse, error)
}

func RegisterGrpcServiceServer(s *grpc.Server, srv GrpcServiceServer) {
	s.RegisterService(&_GrpcService_serviceDesc, srv)
}

func _GrpcService_PiCalc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServiceServer).PiCalc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vgrpc.GrpcService/PiCalc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServiceServer).PiCalc(ctx, req.(*PiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcService_PingCalc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServiceServer).PingCalc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vgrpc.GrpcService/PingCalc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServiceServer).PingCalc(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vgrpc.GrpcService",
	HandlerType: (*GrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PiCalc",
			Handler:    _GrpcService_PiCalc_Handler,
		},
		{
			MethodName: "PingCalc",
			Handler:    _GrpcService_PingCalc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vgrpc.proto",
}
