apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: apis-deployment
  labels:
    app: apis
spec:
  selector:
    matchLabels:
      app: apis
  replicas: 1
  template:
    metadata:
      labels:
        app: apis
    spec:
      containers:
      - name: apis
        image: local/apis
        imagePullPolicy: Never
        ports:
        - name: apis-service
          containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: apis-service
spec:
  type: NodePort
  selector:
    app: apis
  ports:
  - port: 3000
    targetPort: apis-service