// Code generated by protoc-gen-go. DO NOT EDIT.
// source: k8s.proto

package k8s

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// pi input
type PiRequest struct {
	N                    int32    `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PiRequest) Reset()         { *m = PiRequest{} }
func (m *PiRequest) String() string { return proto.CompactTextString(m) }
func (*PiRequest) ProtoMessage()    {}
func (*PiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e25cbc1b2df348ba, []int{0}
}

func (m *PiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PiRequest.Unmarshal(m, b)
}
func (m *PiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PiRequest.Marshal(b, m, deterministic)
}
func (m *PiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PiRequest.Merge(m, src)
}
func (m *PiRequest) XXX_Size() int {
	return xxx_messageInfo_PiRequest.Size(m)
}
func (m *PiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PiRequest proto.InternalMessageInfo

func (m *PiRequest) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

// pi output
type PiResponse struct {
	Out                  string   `protobuf:"bytes,1,opt,name=out,proto3" json:"out,omitempty"`
	Value                float64  `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PiResponse) Reset()         { *m = PiResponse{} }
func (m *PiResponse) String() string { return proto.CompactTextString(m) }
func (*PiResponse) ProtoMessage()    {}
func (*PiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e25cbc1b2df348ba, []int{1}
}

func (m *PiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PiResponse.Unmarshal(m, b)
}
func (m *PiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PiResponse.Marshal(b, m, deterministic)
}
func (m *PiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PiResponse.Merge(m, src)
}
func (m *PiResponse) XXX_Size() int {
	return xxx_messageInfo_PiResponse.Size(m)
}
func (m *PiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PiResponse proto.InternalMessageInfo

func (m *PiResponse) GetOut() string {
	if m != nil {
		return m.Out
	}
	return ""
}

func (m *PiResponse) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// pi input
type PingRequest struct {
	Params               string   `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e25cbc1b2df348ba, []int{2}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetParams() string {
	if m != nil {
		return m.Params
	}
	return ""
}

// pi output
type PingResponse struct {
	Out                  string   `protobuf:"bytes,1,opt,name=out,proto3" json:"out,omitempty"`
	Result               string   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e25cbc1b2df348ba, []int{3}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetOut() string {
	if m != nil {
		return m.Out
	}
	return ""
}

func (m *PingResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GCDRequest struct {
	A                    uint64   `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    uint64   `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GCDRequest) Reset()         { *m = GCDRequest{} }
func (m *GCDRequest) String() string { return proto.CompactTextString(m) }
func (*GCDRequest) ProtoMessage()    {}
func (*GCDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e25cbc1b2df348ba, []int{4}
}

func (m *GCDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GCDRequest.Unmarshal(m, b)
}
func (m *GCDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GCDRequest.Marshal(b, m, deterministic)
}
func (m *GCDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GCDRequest.Merge(m, src)
}
func (m *GCDRequest) XXX_Size() int {
	return xxx_messageInfo_GCDRequest.Size(m)
}
func (m *GCDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GCDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GCDRequest proto.InternalMessageInfo

func (m *GCDRequest) GetA() uint64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *GCDRequest) GetB() uint64 {
	if m != nil {
		return m.B
	}
	return 0
}

type GCDResponse struct {
	Result               uint64   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GCDResponse) Reset()         { *m = GCDResponse{} }
func (m *GCDResponse) String() string { return proto.CompactTextString(m) }
func (*GCDResponse) ProtoMessage()    {}
func (*GCDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e25cbc1b2df348ba, []int{5}
}

func (m *GCDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GCDResponse.Unmarshal(m, b)
}
func (m *GCDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GCDResponse.Marshal(b, m, deterministic)
}
func (m *GCDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GCDResponse.Merge(m, src)
}
func (m *GCDResponse) XXX_Size() int {
	return xxx_messageInfo_GCDResponse.Size(m)
}
func (m *GCDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GCDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GCDResponse proto.InternalMessageInfo

func (m *GCDResponse) GetResult() uint64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*PiRequest)(nil), "k8s.PiRequest")
	proto.RegisterType((*PiResponse)(nil), "k8s.PiResponse")
	proto.RegisterType((*PingRequest)(nil), "k8s.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "k8s.PingResponse")
	proto.RegisterType((*GCDRequest)(nil), "k8s.GCDRequest")
	proto.RegisterType((*GCDResponse)(nil), "k8s.GCDResponse")
}

func init() { proto.RegisterFile("k8s.proto", fileDescriptor_e25cbc1b2df348ba) }

var fileDescriptor_e25cbc1b2df348ba = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcf, 0x6a, 0x83, 0x40,
	0x10, 0xc6, 0x3b, 0x4d, 0x62, 0xeb, 0x24, 0xb4, 0x76, 0x29, 0x21, 0xf5, 0x14, 0x16, 0x0a, 0x42,
	0x41, 0xe8, 0x9f, 0x83, 0x77, 0x03, 0x5e, 0x65, 0xfb, 0x04, 0xab, 0x2c, 0x45, 0x62, 0xd5, 0xee,
	0x6a, 0xde, 0xa6, 0xef, 0x5a, 0xf6, 0x4f, 0xd6, 0x5c, 0x7a, 0xf3, 0x9b, 0xf9, 0xbe, 0x9f, 0x33,
	0xb3, 0x18, 0x1e, 0x33, 0x95, 0x0e, 0xb2, 0x1f, 0x7b, 0xb2, 0x38, 0x66, 0x8a, 0x3e, 0x61, 0x58,
	0x36, 0x4c, 0xfc, 0x4c, 0x42, 0x8d, 0x64, 0x83, 0xd0, 0xed, 0x60, 0x0f, 0xc9, 0x8a, 0x41, 0x47,
	0x3f, 0x10, 0x75, 0x4b, 0x0d, 0x7d, 0xa7, 0x04, 0x89, 0x70, 0xd1, 0x4f, 0xa3, 0xe9, 0x86, 0x4c,
	0x7f, 0x92, 0x47, 0x5c, 0x9d, 0x78, 0x3b, 0x89, 0xdd, 0xf5, 0x1e, 0x12, 0x60, 0x56, 0xd0, 0x67,
	0x5c, 0x97, 0x4d, 0xf7, 0x75, 0x46, 0x6e, 0x31, 0x18, 0xb8, 0xe4, 0xdf, 0xca, 0x25, 0x9d, 0xa2,
	0x19, 0x6e, 0xac, 0xed, 0x5f, 0xfc, 0x16, 0x03, 0x29, 0xd4, 0xd4, 0x8e, 0x86, 0x1f, 0x32, 0xa7,
	0x68, 0x82, 0x58, 0xe4, 0x87, 0x8b, 0x91, 0xb9, 0x49, 0x2d, 0x19, 0x70, 0xad, 0x2a, 0x63, 0x5f,
	0x32, 0xa8, 0xf4, 0x28, 0xc6, 0xe9, 0x7e, 0x31, 0x03, 0xad, 0xdf, 0xa9, 0xb7, 0x5f, 0xc0, 0x75,
	0x21, 0x87, 0xfa, 0x53, 0xc8, 0x53, 0x53, 0x0b, 0xf2, 0x82, 0x41, 0xd9, 0xe4, 0xbc, 0xad, 0xc9,
	0x5d, 0xaa, 0xaf, 0xe5, 0xef, 0x13, 0xdf, 0x7b, 0x6d, 0x91, 0xf4, 0x8a, 0xbc, 0xe2, 0xad, 0xde,
	0xc3, 0xd8, 0x23, 0xd7, 0xf6, 0xdb, 0xc7, 0x0f, 0x17, 0x15, 0x1f, 0x49, 0xf1, 0xa6, 0xc8, 0x0f,
	0x26, 0x61, 0x81, 0xf3, 0x3a, 0x71, 0x34, 0x17, 0xce, 0xfe, 0x2a, 0x30, 0xcf, 0xf5, 0xfe, 0x17,
	0x00, 0x00, 0xff, 0xff, 0xc9, 0x93, 0xbb, 0xfe, 0xbb, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrpcServiceClient is the client API for GrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcServiceClient interface {
	// pi method
	PiCalc(ctx context.Context, in *PiRequest, opts ...grpc.CallOption) (*PiResponse, error)
	PingCalc(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	GCDCalc(ctx context.Context, in *GCDRequest, opts ...grpc.CallOption) (*GCDResponse, error)
}

type grpcServiceClient struct {
	cc *grpc.ClientConn
}

func NewGrpcServiceClient(cc *grpc.ClientConn) GrpcServiceClient {
	return &grpcServiceClient{cc}
}

func (c *grpcServiceClient) PiCalc(ctx context.Context, in *PiRequest, opts ...grpc.CallOption) (*PiResponse, error) {
	out := new(PiResponse)
	err := c.cc.Invoke(ctx, "/k8s.GrpcService/PiCalc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcServiceClient) PingCalc(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/k8s.GrpcService/PingCalc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcServiceClient) GCDCalc(ctx context.Context, in *GCDRequest, opts ...grpc.CallOption) (*GCDResponse, error) {
	out := new(GCDResponse)
	err := c.cc.Invoke(ctx, "/k8s.GrpcService/GCDCalc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcServiceServer is the server API for GrpcService service.
type GrpcServiceServer interface {
	// pi method
	PiCalc(context.Context, *PiRequest) (*PiResponse, error)
	PingCalc(context.Context, *PingRequest) (*PingResponse, error)
	GCDCalc(context.Context, *GCDRequest) (*GCDResponse, error)
}

// UnimplementedGrpcServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGrpcServiceServer struct {
}

func (*UnimplementedGrpcServiceServer) PiCalc(ctx context.Context, req *PiRequest) (*PiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PiCalc not implemented")
}
func (*UnimplementedGrpcServiceServer) PingCalc(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingCalc not implemented")
}
func (*UnimplementedGrpcServiceServer) GCDCalc(ctx context.Context, req *GCDRequest) (*GCDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GCDCalc not implemented")
}

func RegisterGrpcServiceServer(s *grpc.Server, srv GrpcServiceServer) {
	s.RegisterService(&_GrpcService_serviceDesc, srv)
}

func _GrpcService_PiCalc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServiceServer).PiCalc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/k8s.GrpcService/PiCalc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServiceServer).PiCalc(ctx, req.(*PiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcService_PingCalc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServiceServer).PingCalc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/k8s.GrpcService/PingCalc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServiceServer).PingCalc(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcService_GCDCalc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GCDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServiceServer).GCDCalc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/k8s.GrpcService/GCDCalc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServiceServer).GCDCalc(ctx, req.(*GCDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "k8s.GrpcService",
	HandlerType: (*GrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PiCalc",
			Handler:    _GrpcService_PiCalc_Handler,
		},
		{
			MethodName: "PingCalc",
			Handler:    _GrpcService_PingCalc_Handler,
		},
		{
			MethodName: "GCDCalc",
			Handler:    _GrpcService_GCDCalc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "k8s.proto",
}
